name: Sync North American Cities to Neon

on:
  # This event enables the manual "Run workflow" play button in the GitHub UI
  workflow_dispatch:

jobs:
  run-import-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary

      - name: Execute Import Script
        env:
          X_RAPIDAPI_KEY:"435b7b2308msh9eee01fda766b76p159242jsnc76484ed9ed5"
          NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}
        run: python migratory_bird_playground/import_n_american_cities.py
